CREATE TABLE SAMPLE_TABLE (
     COL1 NUMBER
    ,COL2 VARCHAR(10)
    ,COL3 CHAR(10)
    ,COL4 DATE
);
COMMENT ON COLUMN SAMPLE_TABLE.COL1 IS '숫자 타입의 컬럼';
COMMENT ON COLUMN SAMPLE_TABLE.COL2 IS '가변 문자열 컬럼';
COMMENT ON COLUMN SAMPLE_TABLE.COL3 IS '고정 문자열 컬럼';
COMMENT ON COLUMN SAMPLE_TABLE.COL4 IS '날짜 타입의 컬럼';


SELECT COMMENT FROM USER_ALL_TABLES;

SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SAMPLE_TABLE';

SELECT * FROM USER_COL_COMMENTS WHERE TABLE_NAME = 'SAMPLE_TABLE';

DESC SAMPLE_TABLE;

ALTER TABLE SAMPLE_TABLE ADD COL5 NUMBER(5,2);

ALTER TABLE SAMPLE_TABLE MODIFY COL3 VARCHAR2(10);

ALTER TABLE SAMPLE_TABLE RENAME COLUMN COL1 TO ID;

ALTER TABLE SAMPLE_TABLE DROP COLUMN COL3;

ALTER TABLE SAMPLE_TABLE RENAME TO SAM_T;

DESC SAM_T;

DROP TABLE SAM_T;

