CREATE TABLE SAMPLE_TABLE (
     COL1 NUMBER
    ,COL2 VARCHAR(10)
    ,COL3 CHAR(10)
    ,COL4 DATE
);
COMMENT ON COLUMN SAMPLE_TABLE.COL1 IS '숫자 타입의 컬럼';
COMMENT ON COLUMN SAMPLE_TABLE.COL2 IS '가변 문자열 컬럼';
COMMENT ON COLUMN SAMPLE_TABLE.COL3 IS '고정 문자열 컬럼';
COMMENT ON COLUMN SAMPLE_TABLE.COL4 IS '날짜 타입의 컬럼';


SELECT COMMENT FROM USER_ALL_TABLES;

SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SAMPLE_TABLE';

SELECT * FROM USER_COL_COMMENTS WHERE TABLE_NAME = 'SAMPLE_TABLE';